'use client'

import Link from 'next/link'

export default function BlogPost({ post }) {
  return (
    <main className="bg-white dark:bg-gray-900">
      <div className="mx-auto max-w-4xl px-6 py-24 lg:px-8">
        {/* Navigation */}
        <div className="mb-8">
          <Link 
            href="/blog" 
            className="text-sm/6 font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
          >
            ← Back to Blog
          </Link>
        </div>

        {/* Article Header */}
        <header className="mb-12">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
            {post.title}
          </h1>
          <div className="mt-6 flex items-center gap-x-4 text-sm text-gray-500 dark:text-gray-400">
            <time dateTime={post.publishDate}>
              {new Date(post.publishDate).toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </time>
            <span>•</span>
            <span>5 min read</span>
            <span>•</span>
            <span>By Fontana Legal Team</span>
          </div>
        </header>

        {/* Article Content */}
        <article className="prose prose-lg max-w-none dark:prose-invert">
          {post.content ? (
            <div dangerouslySetInnerHTML={{ __html: post.content }} />
          ) : (
            <div>
              <p className="text-lg text-gray-600 dark:text-gray-400 mb-6">
                This article is currently being generated by our AI content system. 
                Please check back soon for comprehensive legal insights.
              </p>
              
              <h2>What We Cover</h2>
              <ul>
                <li>Your legal rights after a car accident in Fontana</li>
                <li>How to deal with insurance companies</li>
                <li>Steps to protect your claim</li>
                <li>When to contact an attorney</li>
              </ul>
              
              <div className="mt-8 p-6 bg-indigo-50 border border-indigo-200 rounded-lg dark:bg-indigo-900/20 dark:border-indigo-800">
                <h3 className="text-lg font-semibold text-indigo-900 dark:text-indigo-100 mb-2">
                  Need Immediate Legal Help?
                </h3>
                <p className="text-indigo-800 dark:text-indigo-200 mb-4">
                  Don't wait for the full article. If you've been injured in a car accident, 
                  time is critical for protecting your rights.
                </p>
                <Link 
                  href="/#contact"
                  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                  Get Free Consultation Now
                </Link>
              </div>
            </div>
          )}
        </article>

        {/* Call to Action */}
        <div className="mt-16 p-8 bg-gray-50 border rounded-lg dark:bg-gray-800 dark:border-gray-700">
          <div className="text-center">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              Injured in a Car Accident?
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-400 mb-6">
              Get the legal help you deserve from experienced Fontana car accident attorneys.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link 
                href="/#contact"
                className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Get Free Consultation
              </Link>
              <Link 
                href="/blog"
                className="inline-flex items-center justify-center px-6 py-3 border border-gray-300 text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-700"
              >
                Read More Articles
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}